"""Generate docs/viva/ANSWER_CARD.md from the committed result files.

    python thesis/scripts/make_answer_card.py

Every number on the card is read from `thesis/numbers.json` and
`artifacts/out_wideband/T4_results.csv`, so the card cannot drift from the dissertation the way
`docs/viva/PART4_examiner_questions.md` did. Regenerate it after any analysis re-run.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BONFERRONI_FAMILY = 6  # three targets x two directions
ALPHA = 0.05
# Effects below this absolute MAE percentage are statistically detectable but practically nil.
NEGLIGIBLE_PCT = 0.5


def _rows() -> list[dict[str, str]]:
    path = ROOT / "artifacts" / "out_wideband" / "T4_results.csv"
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return [r for r in csv.DictReader(handle) if r.get("system") == "ridge"]


def _float(value: str | None) -> float | None:
    try:
        return float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return None


def main() -> None:
    numbers = json.loads((ROOT / "thesis" / "numbers.json").read_text())
    ridge = _rows()
    threshold = ALPHA / BONFERRONI_FAMILY

    survivors, negligible = [], []
    lines = []
    for row in ridge:
        delta = _float(row.get("mae_vs_b2_pct"))
        p = _float(row.get("wilcoxon_p_vs_b2_by_speaker"))
        if delta is None or p is None:
            continue
        passes = p < threshold
        entry = (row["direction"], row["target"], delta, p)
        if passes:
            (negligible if abs(delta) < NEGLIGIBLE_PCT else survivors).append(entry)
        lines.append(
            f"| {row['direction']} | `{row['target']}` | {delta:+.2f} % | {p:.4f} | "
            f"{'**yes**' if passes else 'no'} |"
        )

    human = numbers["human"]["features"]
    pipe = numbers.get("pipeline", {})

    def hv(key: str, field: str) -> str:
        node = human.get(key) or {}
        value = node.get(field)
        return f"{value:.4f}" if isinstance(value, (int, float)) else "n/a"

    dirs = pipe.get("directions", {})
    ident = {k: v.get("identity_pct_of_ceiling", float("nan")) for k, v in dirs.items()}
    ceiling = next(
        (
            v.get("human_target_speaker_similarity_speaker_mean")
            for v in dirs.values()
            if v.get("human_target_speaker_similarity_speaker_mean")
        ),
        float("nan"),
    )

    out = [
        "# Answer card — generated, authoritative",
        "",
        "> Generated by `thesis/scripts/make_answer_card.py` from `thesis/numbers.json` and",
        "> `artifacts/out_wideband/T4_results.csv`. **Study from this file, not from**",
        "> **`PART4_examiner_questions.md`**, which rehearses the superseded analysis.",
        f"> Provenance: commit `{numbers.get('provenance', {}).get('git_commit', '?')}`.",
        "",
        "## The prosody-prediction table (the one that gets attacked)",
        "",
        (
            f"Bonferroni threshold for a family of {BONFERRONI_FAMILY} at α={ALPHA}: "
            f"**p < {threshold:.4f}**."
        ),
        "",
        "| Direction | Target | ΔMAE vs B2 | speaker-clustered *p* | survives Bonferroni |",
        "|---|---|---|---|---|",
        *lines,
        "",
        "### The answer to *“does it survive multiple-comparison correction?”*",
        "",
        f"**Yes — {len(survivors)} of {BONFERRONI_FAMILY}, both pitch-range results:**",
        *[
            f"- {d} `{t}`: {v:+.2f} % MAE, p = {p:.4f} — survives Bonferroni, Holm and BH at 5 %."
            for d, t, v, p in survivors
        ],
        "",
        (
            f"**Volunteer this caveat before the panel finds it:** {len(negligible)} further\n"
            "result clears the same threshold with an effect size of practically zero —"
        ),
        *[
            (
                f"- {d} `{t}`: {v:+.2f} % MAE, p = {p:.4f}. Significance on a zero-sized\n"
                "effect; the ridge selected λ=1e6 and collapsed into B2 by itself."
            )
            for d, t, v, p in negligible
        ],
        "",
        "So the honest sentence is: *“the two pitch-range improvements survive family-wise",
        "correction; a third result is significant but its effect size is 0.02 %, which I report",
        "as a null rather than a finding.”*",
        "",
        "## Cross-lingual prosody transfer — within-speaker is the honest column",
        "",
        "| Measure | Human pooled | **Human within-speaker** |",
        "|---|---|---|",
        f"| F0 level | {hv('f0_mean', 'pooled_r')} | **{hv('f0_mean', 'within_r')}** |",
        f"| F0 range | {hv('f0_std', 'pooled_r')} | **{hv('f0_std', 'within_r')}** |",
        f"| Duration | {hv('duration', 'pooled_r')} | **{hv('duration', 'within_r')}** |",
        (
            f"| Speaking rate | {hv('speaking_rate', 'pooled_r')} | "
            f"**{hv('speaking_rate', 'within_r')}** |"
        ),
        "",
        "Quote the **within-speaker** figure. The pooled figure absorbs stable between-speaker",
        "variation that voice cloning already carries, so it counts identity twice as prosody.",
        "",
        "## Numbers that have NOT changed",
        "",
        (
            f"- Identity: **{ident['en-es']:.1f} %** (en-es) and **{ident['es-en']:.1f} %**\n"
            f"  (es-en) of a human ceiling of **{ceiling:.3f}**."
        ),
        (
            f"- Synthesis: {pipe.get('attempted', 870)} attempted, "
            f"{pipe.get('attempted', 870) - pipe.get('failed', 2)} succeeded, {pipe.get('failed', 2)} failed."
        ),
        "- Fine-tune: BLEU 23.98→26.31 (en-es), 26.79→30.02 (es-en). Register adaptation, not",
        "  adequacy. Epoch 2 selected on dev in both directions.",
        "- Cascade cost: 1.84 and 3.34 BLEU. Both sides decode with beam 4 (MarianMT ships",
        "  `num_beams=4` in its `generation_config`).",
        "",
        "## Three questions to have a rehearsed answer for",
        "",
        "1. **“Is 1.52× an average?”** No. That is a ratio of pooled means. The **median**",
        "   per-utterance ratio is **1.43×**, the mean of per-utterance ratios is **1.84×**, and",
        "   **25.1 %** exceed 2.0×. The per-segment distribution is what binds the WORLD clamp.",
        "2. **“Why does §4.10 end at 0.698 when your band sweep says 0.888?”** Different",
        "   statistics: §4.10 and Table 4.4 use the **mean** utterance F0; the band sweep uses the",
        "   **median**, because a wide band's octave doublings move a mean far more than a median.",
        "3. **“Did the F0 correction improve your model?”** No — it corrected the *measurement*.",
        "   Never present 0.048→0.820 as a model gain.",
        "",
    ]
    target = ROOT / "docs" / "viva" / "ANSWER_CARD.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {target}  ({len(survivors)} real survivors, {len(negligible)} negligible)")


if __name__ == "__main__":
    main()
