"""Generate MODEL_CARD.md for the open-source release, entirely from committed artefacts.

    python -m bilingual_voice.prosody_card build --out MODEL_CARD.md

Deliberately a generator rather than a hand-written document. A figure in this project once
carried a hardcoded "63-107%" when the data said 69-128%, and a model card is exactly the kind of
document that gets written once and then quietly drifts from the numbers it describes. Everything
below is read from `artifacts/prosody_net/` and `artifacts/ladder/`; if an artefact is missing, the
section says so instead of inventing a value.
"""

from __future__ import annotations

import argparse
from pathlib import Path

SPLIT_NOTE = (
    "Speaker-component-disjoint 70/15/15 split, seed 498. Splits are formed over the union-find "
    "components of the speaker graph, so no speaker appears in more than one split."
)


LIMITATIONS = """## Limitations — read these before citing anything above

This section is written by hand. Its numbers were measured in the review of 28 September 2026 and
are not regenerated by `prosody_card build`.

- **The ladder's pitch-LEVEL results are not valid.** `prosody_apply.inject` measured the pitch
  shift against the caller's (pyin) level but added it to WORLD's own median, so the level written
  was 0.65-1.09 st off on median and more than 1 st off for 37-55 % of utterances, differently per
  arm. Fixed on 28 September 2026. On a 185-utterance re-render with the fix, the es-en ProsoCNN
  pitch-level advantage over S1 went from -0.31 [-0.65, -0.04] to +0.07 [-0.08, +0.22] st, and S1
  then beat both models on es-en level. The ladder tables above predate the fix: re-render before
  citing any pitch-level column. The pitch-span gain (ProsoCNN en-es -0.13 [-0.20, -0.06] st) and
  the contour-shape gain (ProsoMLP +0.03 / +0.05 r) survive on a common, gated set.
- **S3 is a round-trip fidelity check, not a ceiling.** It imposes the human target's own
  measurements and is scored against the same measurements through the same tracker.
- **Ladder scoring has no plausibility gate on generated audio, and each arm is scored on its own
  subset** (n = 337-345). Gate every arm and score on the common set before comparing arms.
- **These models do not replace XTTS, Whisper or MarianMT.** They add a prosody-transfer component
  that the pretrained cascade does not have. Any claim that they beat a production TTS system would
  be false.
- **Not state of the art.** 6,284 and 4,796 parameters trained on 1,633 pairs per direction.
- **Injection costs speaker similarity and intelligibility.** ECAPA falls from 0.440 (raw XTTS) to
  ~0.359 and WER rises from 0.100 to ~0.148 (en-es). The WORLD round-trip costs 0.028 ECAPA (es-en
  0.026), retiming 0.035-0.036 (es-en 0.022) and pitch editing 0.017-0.020; the models' own
  predictions cost nothing beyond the copy baseline. With the thesis's own speaker-mean definition on
  the ladder rows, identity falls from 92.0 % to 75.2 % of the human ceiling in en-es and from 84.1 %
  to 70.7 % in es-en.
- **Retiming trades differently than hoped.** Pitch-only variants recover 31-52 % of the WER cost
  (one of four intervals excludes zero); pitch MAE is better in 2 of 4 cases and span MAE in 1 of 4.
- **Duration.** 1.26x and 2.03x are means of per-utterance ratios; the medians are about 1.0-1.05
  and 1.44. The 0.5x clamp binds on 29.9 % of en-es and 8-12 % of es-en utterances. The overrun is
  XTTS's slow speaking rate, not translation length (MT output length matches the human target).
- **Contour shape is only partly recovered.** ProsoMLP raises the predicted-contour correlation above
  the copy-plus-offset baseline (0.343 vs 0.316 en-es; 0.360 vs 0.321 es-en); ProsoCNN does not.
  The copy-source baseline itself correlates at 0.302 on test (0.33 across splits). The audio-domain
  oracle values (0.588 / 0.639) are a different measurement and are not comparable.
- **The linear control is not matched.** ridge_full picks lambda by the one-SE rule (biased towards
  B2) while the networks pick by best dev loss. With best-dev lambda the ridge ties or beats ProsoMLP
  on 4 of 6 targets; ProsoCNN keeps a clear margin mainly on en-es pitch span.
- **ProsoMLP is worse than baseline on es-en pitch level** (+1.09 %).
- **No listening study.** Every number here is an objective measure.
- **The +/-3 semitone level cap binds** on 7.5-12.6 % of S1/S2 utterances and on 19.5 % (en-es) /
  15.9 % (es-en) of oracle utterances.
- **The MT word-count input contains degenerate MarianMT repetition loops** (up to 282 words) and is
  not clipped. Capping it at 3x the source and retraining moved the headline results by at most
  0.56 points. The MT(gold)-MT(asr) correlation of 0.611 is driven by two loop rows (0.80 without).
- **DRAL pairs are re-enactments, not translations**, so these models learn how one bilingual
  speaker's prosody maps across their own two languages.
- **The audio-domain ladder was run twice** (the first run imposed contour shape without amplitude).
  The scalar results above are unaffected -- the models were frozen before test was touched.
"""

REPRODUCING = """## Reproducing

```bash
python -m bilingual_voice.contours    extract data/splits/dral_manifest_with_text.csv artifacts/contours --jobs 6
python -m bilingual_voice.mt_words    build   data/splits/dral_manifest_with_text.csv artifacts/mt_words.csv
python -m bilingual_voice.prosody_net prepare --direction en-es
python -m bilingual_voice.prosody_net overfit --arch mlp --direction en-es   # sanity gate
python -m bilingual_voice.prosody_net train   --arch mlp --direction en-es
python -m bilingual_voice.prosody_eval report --split dev
python -m bilingual_voice.prosody_ladder render  results/synthesis_test.csv --jobs 6
python -m bilingual_voice.prosody_ladder measure artifacts/ladder results/synthesis_test.csv
python -m bilingual_voice.prosody_ladder report  artifacts/ladder --synthesis-csv results/synthesis_test.csv
python -m bilingual_voice.prosody_figures all
```

Seeds are fixed (498-502). Training is CPU-only and takes seconds per model.
"""

def _read_csv(path: Path):
    import pandas as pd

    return pd.read_csv(path) if path.exists() else None


def _fmt(value, digits: int = 4) -> str:
    import math

    if value is None:
        return "—"
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    return "—" if math.isnan(number) else f"{number:.{digits}f}"


def _architecture_section(netdir: Path) -> str:
    import torch

    lines = [
        "## Architectures",
        "",
        "Both models are written from scratch in PyTorch and trained from random initialisation.",
        "**No pretrained weights are used in either model.**",
        "",
    ]
    for arch, name, description in (
        (
            "mlp",
            "ProsoMLP",
            (
                "A residual MLP over the source contour's DCT coefficients.\n"
                "`Linear(16→64) → LayerNorm → GELU → Dropout(0.1) → "
                "Linear(64→64) → LayerNorm → GELU → Dropout(0.1) → Linear(64→12)`"
            ),
        ),
        (
            "cnn",
            "ProsoCNN",
            (
                "A 1-D CNN reading the raw 64-point contour, bypassing the DCT compression.\n"
                "`Conv1d(1→16,k=5) → GELU → Conv1d(16→16,k=5) → GELU → "
                "mean+max pool → concat 8 scalars → Linear(40→64) → GELU → Linear(64→12)`"
            ),
        ),
    ):
        found = sorted(netdir.glob(f"{arch}-*.pt"))
        if not found:
            lines += [f"### {name}", "", "_no checkpoint found_", ""]
            continue
        blob = torch.load(found[0], map_location="cpu", weights_only=False)
        config = blob["config"]
        from .prosody_net import build_model, count_parameters

        params = count_parameters(build_model(arch, config["hidden"], config["dropout"]))
        lines += [
            f"### {name} — {params:,} parameters",
            "",
            description,
            "",
            (
                f"- Trained on: `{', '.join(sorted(p.stem for p in found))}` "
                f"({len(blob['seeds'])}-seed ensemble, seeds {blob['seeds']})"
            ),
            (
                f"- Optimiser: AdamW, lr {config['lr']}, weight decay "
                f"{config['weight_decay']}, batch {config['batch_size']}, gradient clip 1.0"
            ),
            (
                f"- Early stopping on dev loss, patience {config['patience']}, "
                f"max {config['epochs']} epochs"
            ),
            (
                "- Loss: SmoothL1 on standardised residuals; contour coefficients weighted "
                f"{config['aux_weight']} relative to the three reported targets"
            ),
            "- Device: CPU (at this size, MPS kernel-launch overhead exceeds the arithmetic)",
            "",
        ]
    lines += [
        "### The output layer is initialised to zero — on purpose",
        "",
        "Every target is parameterised as a **residual from baseline B2** (copy the source value,",
        "plus one global offset fitted on train). With a zero-initialised head the prediction at",
        "step 0 *is* B2, exactly. The model can only move away from the baseline if the dev loss",
        "improves, so it is structurally impossible for it to start out worse than the published",
        "baseline. A contract test asserts a fresh model outputs exactly zero.",
        "",
    ]
    return "\n".join(lines)


def _results_section(netdir: Path, split: str) -> str:
    table = _read_csv(netdir / f"results-{split}.csv")
    if table is None:
        return f"## Results ({split})\n\n_`results-{split}.csv` not found — run `prosody_eval`._\n"

    lines = [
        f"## Results — {split} split",
        "",
        "Mean absolute error against the human target. **B2** is the baseline the thesis reports;",
        "**ridge_full** is the linear model given the *same 16 inputs* as ProsoMLP, so a neural win",
        "is attributable to the architecture rather than to extra features.",
        "",
    ]
    systems = [
        "B0_copy_source",
        "B2_copy_plus_offset",
        "ridge_t0",
        "ridge_full",
        "ProsoMLP",
        "ProsoCNN",
    ]
    for direction in sorted(table["direction"].unique()):
        lines += [
            f"### {direction}",
            "",
            "| target | " + " | ".join(s.replace("_", " ") for s in systems) + " |",
            "|---|" + "---|" * len(systems),
        ]
        for target in ("f0_mean_st", "f0_std_st", "log_dur_ratio"):
            part = table[(table["direction"] == direction) & (table["target"] == target)]
            if part.empty:
                continue
            cells = []
            b2_row = part[part["system"] == "B2_copy_plus_offset"]
            b2 = float(b2_row["mae"].iloc[0]) if not b2_row.empty else None
            for system in systems:
                row = part[part["system"] == system]
                if row.empty:
                    cells.append("—")
                    continue
                mae = float(row["mae"].iloc[0])
                if system == "B2_copy_plus_offset" or b2 is None:
                    cells.append(f"{mae:.4f}")
                else:
                    cells.append(f"{mae:.4f} ({100 * (mae - b2) / b2:+.1f}%)")
            lines.append(f"| `{target}` | " + " | ".join(cells) + " |")
        lines.append("")

    speakers = table["n_speakers"].dropna()
    if len(speakers):
        n = int(speakers.max())
        lines += [
            "### Statistical inference, and its limit",
            "",
            (
                f"Errors are correlated within a speaker, and the {split} split holds only "
                f"**{n} speakers**. Two speaker-aware tests are reported: a Wilcoxon "
                "signed-rank test over"
            ),
            "per-speaker mean absolute errors, and a bootstrap CI that resamples speakers rather",
            "than recordings.",
            "",
            (
                f"With {n} speakers the smallest attainable two-sided signed-rank *p* is "
                f"**{2 / 2**n:.5f}**. Holm correction is applied over a pre-specified family of 12"
            ),
            "confirmatory comparisons (2 models x 3 targets x 2 directions); the correction over",
            "all table rows is also reported as a conservative sensitivity check.",
            "",
            "**None of the 12 network comparisons is significant after Holm correction.** The",
            "limit is not the number of speakers: on the same 14 speakers the thesis's linear",
            "ridge improves pitch span for all 14 (p at the floor). The networks' mean gains",
            "come from a few speakers -- pitch span improves for 10 or 11 of 14, and three",
            "speakers carry 68-87 % of the gain. The speaker-resampling bootstrap intervals are",
            "descriptive only: with 14 clusters they excluded zero in 10-14 % of simulated null",
            "datasets at a nominal 5 %.",
            "",
        ]
    return "\n".join(lines)


def _ladder_section(ladder_dir: Path) -> str:
    table = _read_csv(ladder_dir / "ladder_summary.csv")
    if table is None:
        return "## The evaluation ladder\n\n_`ladder_summary.csv` not found — run `prosody_ladder`._\n"

    lines = [
        "## The evaluation ladder",
        "",
        "Each arm imposes one system's predicted prosody on audio XTTS **already produced**, so the",
        "words, the voice and the vocoder path are identical across arms and only the prosody",
        "differs. No speech is re-synthesised.",
        "",
        "| arm | what it is |",
        "|---|---|",
        "| `S0` | raw XTTS, untouched |",
        "| `S0_identity` | WORLD analysed and resynthesised with no edit — the vocoder's own footprint |",
        "| `S1_copy` | B2's prediction imposed. **This is the baseline the models must beat** |",
        "| `S2_mlp` / `S2_cnn` | the from-scratch models' predictions imposed |",
        "| `S3_dct` | the human target's own prosody, through the 8-coefficient DCT bottleneck |",
        "| `S3_full` | the human target's own prosody at full contour resolution — the ceiling |",
        "| `*_pitch` | as above but pitch ONLY, timing untouched — isolates the retiming's cost |",
        "",
        "`S3 − S3_dct` is what the representation costs; `S3_dct − S2` is what the predictor costs;",
        "`S2 − S1` is what the model buys.",
        "",
    ]
    columns = [
        ("n", "n", 0),
        ("f0_mean_mae_st", "pitch MAE (st)", 4),
        ("f0_std_mae_st", "span MAE (st)", 4),
        ("shape_r_mean", "contour r", 3),
        ("duration_ratio", "dur / target", 3),
        ("ecapa_mean", "ECAPA", 4),
        ("wer_mean", "WER", 4),
    ]
    present = [c for c in columns if c[0] in table.columns]
    for direction in sorted(table["direction"].unique()):
        lines += [
            f"### {direction}",
            "",
            "| arm | " + " | ".join(label for _c, label, _d in present) + " |",
            "|---|" + "---|" * len(present),
        ]
        part = table[table["direction"] == direction]
        from .prosody_ladder import ARMS

        for arm in ARMS:
            row = part[part["arm"] == arm]
            if row.empty:
                continue
            cells = [_fmt(row[c].iloc[0], d) for c, _label, d in present]
            lines.append(f"| `{arm}` | " + " | ".join(cells) + " |")
        lines.append("")
    return "\n".join(lines)


def _data_section(netdir: Path) -> str:
    lines = ["## Training data", "", SPLIT_NOTE, ""]
    for direction in ("en-es", "es-en"):
        path = netdir / f"dataset-{direction}.npz"
        if not path.exists():
            continue
        import numpy as np

        with np.load(path, allow_pickle=False) as data:
            split = data["split"]
            speakers = data["speaker"]
            counts = {s: int((split == s).sum()) for s in ("train", "dev", "test")}
            lines.append(
                f"- **{direction}**: {counts['train']} train / {counts['dev']} dev / "
                f"{counts['test']} test pairs; "
                f"{len(set(speakers[split == 'test']))} test speakers"
            )
    lines += [
        "",
        "Source: **DRAL** (Dialogs Re-enacted Across Languages), restricted to pairs where one",
        "bilingual speaker performed both sides. DRAL's second-language side is a conversational",
        "**re-enactment, not a literal translation** — so these models learn how a speaker's",
        "prosody maps across their own two languages, which is exactly the quantity of interest,",
        "but the pairs are not translation pairs and should not be described as such.",
        "",
        "### Inputs (16), and the leak that was avoided",
        "",
        "Eight DCT coefficients of the source contour, plus the source's pitch level, pitch span,",
        "log duration, voiced ratio, word count and speaking rate, plus the **machine",
        "translation's** word count and the log word ratio.",
        "",
        "The target word count is taken from machine translation, **never from the human target",
        "transcript**. The human target is the thing being predicted and its length is most of the",
        "answer; a model given that number would post a duration score it could never reproduce in",
        "deployment. MT output is available before synthesis, so using it is causally legitimate.",
        "",
        "One residual mismatch is measured rather than assumed: MT is run over the gold source",
        "transcript because train/dev have no ASR pass, while deployment translates Whisper output.",
        "MT(gold) and MT(asr) word counts correlate at *r* = 0.611 (0.80 without two runaway",
        "repetition-loop rows; MAE 1.32 words), so the test",
        "split additionally carries deployment-realistic ASR-derived features and both are reported",
        "(`ProsoMLP` vs `ProsoMLP_deploy`).",
        "",
    ]
    return "\n".join(lines)


def _limitations_section() -> str:
    return LIMITATIONS


def build(netdir: Path, ladder_dir: Path, out: Path, split: str = "test") -> Path:
    header = [
        "# ProsoMLP and ProsoCNN — prosody predictors for cross-lingual speech",
        "",
        "Two small neural models that predict the prosody of a translated utterance from the",
        "source utterance, trained from scratch on DRAL. They fill a gap in the cascaded",
        "speech-to-speech pipeline (Whisper → MarianMT → XTTS), which preserves *speaker identity*",
        "well but transfers almost no utterance-level *prosody*.",
        "",
        "The source is in this repository (add a LICENSE before calling it open source). The",
        "tables are generated from the committed artefacts by",
        "`python -m bilingual_voice.prosody_card build`; the Limitations section is written by",
        "hand.",
        "",
    ]
    sections = [
        "\n".join(header),
        _architecture_section(netdir),
        _data_section(netdir),
        _results_section(netdir, split),
        _ladder_section(ladder_dir),
        _limitations_section(),
        REPRODUCING,
    ]
    out.write_text("\n".join(sections), encoding="utf-8")
    print(f"wrote {out} ({out.stat().st_size:,} bytes)")
    return out


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="bilingual_voice.prosody_card")
    sub = parser.add_subparsers(dest="command", required=True)
    bld = sub.add_parser("build")
    bld.add_argument("--netdir", type=Path, default=Path("artifacts/prosody_net"))
    bld.add_argument("--ladder", dest="ladder_dir", type=Path, default=Path("artifacts/ladder"))
    bld.add_argument("--out", type=Path, default=Path("MODEL_CARD.md"))
    bld.add_argument("--split", choices=("dev", "test"), default="test")
    args = parser.parse_args(argv)
    if args.command == "build":
        build(args.netdir, args.ladder_dir, args.out, args.split)


if __name__ == "__main__":
    main()
